# Generated by Django 2.0 on 2017-12-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('ZID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('InnerIP', models.CharField(max_length=50)),
                ('InnerPort', models.CharField(max_length=50)),
                ('OuterIP', models.CharField(max_length=50)),
                ('OuterPort', models.CharField(max_length=50)),
                ('AddDate', models.DateTimeField(auto_now_add=True)),
                ('ModifyDate', models.DateTimeField(auto_now=True)),
                ('IsVM', models.BooleanField(default=1)),
            ],
        ),
    ]
