# Generated by Django 2.0 on 2018-01-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1228', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='ZHaveVIP',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hosts',
            name='ZVIP',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
