# Generated by Django 2.0 on 2018-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1228', '0002_auto_20180106_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_IP',
            fields=[
                ('ZID', models.AutoField(primary_key=True, serialize=False)),
                ('ZIP', models.CharField(max_length=50)),
                ('ZIPType', models.IntegerField()),
                ('ZMask', models.CharField(max_length=50)),
                ('ZGateway', models.CharField(max_length=50)),
                ('ZWanIP', models.CharField(max_length=50)),
                ('ZSwitch', models.IntegerField()),
                ('ZRouter', models.IntegerField()),
                ('ZUserGroup', models.IntegerField()),
                ('ZProjGroup', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='hosts',
            new_name='Z_hosts',
        ),
    ]
