# Generated by Django 2.0 on 2018-01-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1228', '0003_auto_20180106_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_User',
            fields=[
                ('ZID', models.AutoField(primary_key=True, serialize=False)),
                ('ZName', models.CharField(max_length=50)),
                ('ZPassword', models.CharField(max_length=255)),
                ('ZEmail', models.EmailField(max_length=254, unique=True)),
                ('ZUserGroup', models.IntegerField()),
                ('ZProjGroup', models.IntegerField()),
                ('ZIsDismission', models.BooleanField(default=0)),
                ('ZisDisabled', models.BooleanField(default=0)),
            ],
        ),
    ]
